const canvas = document.getElementById('canvas1');
const ctx = canvas.getContext('2d')
canvas.width = window.innerWidth;
canvas.height = window.innerHeight;

let gradient = ctx.createLinearGradient(0,canvas.height,canvas.width,0); //start1, start2, end1, end2
//let gradient = ctx.createRadialGradient(canvas.width/2,canvas.height/2,100,canvas.width/2,canvas.height/2,200); //x1,y1,radius1,x2,y2,radius2

// gradient.addColorStop(0,'red'); //what colors we want the gradient to be made out of
// gradient.addColorStop(0.2,'yellow'); //what colors we want the gradient to be made out of
// gradient.addColorStop(0.4,'green'); //what colors we want the gradient to be made out of
// gradient.addColorStop(0.6,'cyan'); //what colors we want the gradient to be made out of
// gradient.addColorStop(0.8,'blue'); //what colors we want the gradient to be made out of
// gradient.addColorStop(1,'magenta'); //what colors we want the gradient to be made out of

gradient.addColorStop(0,'#F0FFFF'); //what colors we want the gradient to be made out of
gradient.addColorStop(0.2,'#89CFF0'); //what colors we want the gradient to be made out of
gradient.addColorStop(0.4,'#0096FF'); //what colors we want the gradient to be made out of
gradient.addColorStop(0.6,'#6495ED'); //what colors we want the gradient to be made out of
gradient.addColorStop(0.8,'#7393B3'); //what colors we want the gradient to be made out of
gradient.addColorStop(1,'#6082B6'); //what colors we want the gradient to be made out of







class Symbol {
    constructor(x,y,fontSize,canvasHeight){
        this.characters = "アァカサタナハマヤャラワガザダバパイィキシチニヒミリヰギジヂビピウゥクスツヌフムユュルグズブヅプエェケセテネヘメレゲゼデベペオォコソトノホモヨョロヲゴゾドボポヴッンあぁいぃうぅえぇおぉかきくけこさしすせそたちつってとなにぬねのはひふへほまみむめもやゃゆゅよょらりるれろわゐをん0123456789";
        this.x = x;
        this.y = y;
        this.fontSize = fontSize;
        this.text = '';
        this.canvasHeight = canvasHeight;
    }
    draw(context){
        this.text = this.characters.charAt(Math.floor(Math.random()*this.characters.length));
        context.fillText(this.text, this.x * this.fontSize, this.y * this.fontSize);
        if (this.y * this.fontSize > this.canvasHeight && Math.random() > 0.99){ //the higher the decimal number, the more vertical
            this.y = 0;
        } else{
            this.y += 1;
        }
    }
}


class Effect{
    constructor(canvasWidth,canvasHeight){
        this.canvasWidth = canvasWidth;
        this.canvasHeight = canvasHeight;
        this.fontSize = 36;
        this.columns = this.canvasWidth / this.fontSize;
        this.symbols = [];
        this.#initialize();
        //console.log(this.symbols);
    }
    #initialize(){ //private method
         for (let i = 0; i < this.columns; i++){
             this.symbols[i] = new Symbol(i, 0, this.fontSize, this.canvasHeight);
         }
    }
    resize(width,height){
        this.canvasWidth = width;
        this.canvasHeight = height;
        this.columns = this.canvasWidth / this.fontSize;
        this.symbols = [];
        this.#initialize();
    }
}

const effect = new Effect(canvas.width, canvas.height);
let lastTime = 0;
const fps = 60;
const nextFrame = 3000/fps;
let timer = 0;


function startAnimation(timeStamp){ //auto-generated by requestAnimationFrame
    const deltaTime = timeStamp - lastTime;
    lastTime = timeStamp;
    if (timer > nextFrame){
        //ctx.fillStyle = 'rgba(249, 246, 238, 0.1)'; //bone white
        ctx.fillStyle = 'rgba(220,220,220,.2)'; //silver
        ctx.textAlign = 'center'; //corrects for Japanese and Latin characters being centered differently
        ctx.fillRect(0,0,canvas.width,canvas.height); //makes the symbols disappear
        //ctx.fillStyle = "#0aff0a"; //better to do it here than the draw() method that way it is only called once per frame rather than for every symbol per frame

        ctx.fillStyle = gradient;
        ctx.font = effect.fontSize + 'px monospace'; //monospace characters have pixels which have the same horizontal space
        effect.symbols.forEach(symbol => symbol.draw(ctx));
        timer = 0;
    } else {
        timer += deltaTime;
    }

    animationId = requestAnimationFrame(startAnimation);

}


startAnimation(0);
//animate(0); //0 is for requestAnimation framerate





// Event listener for the 'No Rain' button
document.getElementById('none-animation').addEventListener('click', function () {
    cancelAnimationFrame(animationId);
    ctx.clearRect(0, 0, canvas.width, canvas.height);
    document.body.style.backgroundColor = '#D3D3D3'; // Set background color
});


// Event listener for the 'No Rain' button
document.getElementById('street-rain-animation').addEventListener('click', function () {
    startAnimation(0);
});







//For Music
document.addEventListener("DOMContentLoaded", function () {
    const audioPlayer = document.getElementById('audio-player');

    // Function to play audio based on the selected option
    function playMusic(src) {
        audioPlayer.src = src;
        audioPlayer.play();
    }


    // Event listeners for the dropdown options
    document.getElementById('none-music').addEventListener('click', function () {
        audioPlayer.pause();
        audioPlayer.currentTime = 0; // Reset the audio to the start
    });

    document.getElementById('street-rain-music').addEventListener('click', function () {
        playMusic('big_drops_rain.mp3'); // Update with correct file path
    });

    document.getElementById('thunderstorm-music').addEventListener('click', function () {
        playMusic('thunderstorm.mp3'); // Update with correct file path
    });

    document.getElementById('lofi-rain-music').addEventListener('click', function () {
        playMusic('summer_rain_lofi.mp3'); // Update with correct file path
    });
});




window.addEventListener('resize',function(){
    canvas.width = window.innerWidth;
    canvas.height = window.innerHeight;
    effect.resize(canvas.width, canvas.height)
});
